### ISSUE TITLE
Getting Build issue in Ubuntu 20.04 Error: Undefined reference to pthread_create 

### ISSUE THREAD

**Issue by singhalshubham03** [oneapi-src/level-zero-tests#12]
Hello team,

I am getting the build issue in building the level-zero-tests for all tests with the procedure provided in below path:
https://github.com/oneapi-src/level-zero-tests/blob/master/BUILD.md

_```
Run Build Command(s):/usr/bin/make cmTC_2cd5e/fast && /usr/bin/make -f CMakeFiles/cmTC_2cd5e.dir/build.make CMakeFiles/cmTC_2cd5e.dir/build

make[1]: Entering directory '/home/gta/level-zero-tests-master/build/CMakeFiles/CMakeTmp'

Building C object CMakeFiles/cmTC_2cd5e.dir/src.c.o

/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_2cd5e.dir/src.c.o   -c /home/gta/level-zero-tests-master/build/CMakeFiles/CMakeTmp/src.c

Linking C executable cmTC_2cd5e

/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2cd5e.dir/link.txt --verbose=1

/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_2cd5e.dir/src.c.o  -o cmTC_2cd5e

/usr/bin/ld: CMakeFiles/cmTC_2cd5e.dir/src.c.o: in function `main':

src.c:(.text+0x46): undefined reference to `pthread_create'

/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'

/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'

collect2: error: ld returned 1 exit status

make[1]: *** [CMakeFiles/cmTC_2cd5e.dir/build.make:87: cmTC_2cd5e] Error 1

make[1]: Leaving directory '/home/gta/level-zero-tests-master/build/CMakeFiles/CMakeTmp'

make: *** [Makefile:121: cmTC_2cd5e/fast] Error 2
```_

Can someone please help on this issue

**Comment by bmyates** [comment]
Hi, I don't recognize that log output.  I'm not sure what `cmTC_2cd5e` is. Could you post full log output for each step?

**Comment by singhalshubham03** [comment]
Please find the CMakeError.log and CMakeOutput.log file along with the output display on executing the cmake command.
[CMakeError.log](https://github.com/oneapi-src/level-zero-tests/files/6774178/CMakeError.log)
[CMakeOutput.log](https://github.com/oneapi-src/level-zero-tests/files/6774179/CMakeOutput.log)

Output Displays on executing the """
![image](https://user-images.githubusercontent.com/86722041/124699074-bdfa6180-df07-11eb-911a-36a69c7fb9a6.png)
"""
`-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/clang_tools.cmake:20 (message):
  clang-format-7 not found.  clang-format and clang-format-check targets will
  be disabled.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)


-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37")
-- Found Git: /usr/bin/git (found version "2.25.1")
CMake Error at CMakeLists.txt:38 (add_subdirectory):
  The source directory

    /home/gta/level-zero-tests-master/third_party/googletest

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:39 (add_library):
  add_library cannot create ALIAS target "GTest::GTest" because target
  "gtest" does not already exist.


CMake Error at CMakeLists.txt:40 (add_library):
  add_library cannot create ALIAS target "GMock::GMock" because target
  "gmock" does not already exist.


-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.65") found components: log program_options timer chrono system
-- Found LevelZero: /usr/local/include
-- LevelZero_LIBRARIES: /usr/local/lib/libze_loader.sodl
-- LevelZero_INCLUDE_DIRS: /usr/local/include
-- Found Python3: /usr/bin/python3.8 (found version "3.8.5") found components: Interpreter Development
-- Found SWIG: /usr/bin/swig4.0 (found version "4.0.1")
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/UseSWIG.cmake:607 (message):
  Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
  "cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

Call Stack (most recent call first):
  zesysman/CMakeLists.txt:16 (swig_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.16/Modules/UseSWIG.cmake:460 (message):
  Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
  flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/UseSWIG.cmake:702 (SWIG_ADD_SOURCE_TO_MODULE)
  zesysman/CMakeLists.txt:16 (swig_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at /usr/share/cmake-3.16/Modules/UseSWIG.cmake:828 (message):
  SWIG_LINK_LIBRARIES is deprecated.  Use TARGET_LINK_LIBRARIES instead.
Call Stack (most recent call first):
  zesysman/CMakeLists.txt:22 (swig_link_libraries)


-- PAPI library not found, hardware counter support disabled
-- Adding ze_nano
-- Adding ze_peak
-- Adding ze_pingpong
-- Adding ze_image_copy
-- Adding ze_bandwidth
-- Adding ze_peer
-- Adding test_barrier
-- Adding test_cmdlist
-- Adding test_cmdqueue
-- Adding test_copy
-- Adding test_context
-- Adding test_device
-- Adding test_driver_init_flag_none
-- Adding test_driver_init_flag_gpu
-- Adding test_driver
-- Adding test_event
-- Adding test_fence
-- Adding test_image
-- Adding test_ipc
-- Adding test_ipc_memory
-- Adding test_ipc_multidevice
-- Adding test_ipc_multisubdevice
-- Adding test_ipc_p2p_memory
-- Adding test_memory
-- Adding test_memory_overcommit
-- Adding test_module
-- Adding test_p2p
-- Adding test_residency
-- Adding test_sampler
-- Adding test_template
-- Adding test_usm
-- Adding test_multithread
-- Adding test_multiprocess
-- Adding test_api_tracing
-- Adding test_metric
-- Adding test_pin
-- Adding test_sysman_pci
-- Adding test_sysman_frequency
-- Adding test_sysman_standby
-- Adding test_sysman_power
-- Adding test_sysman_diagnostics
-- Adding test_sysman_events
-- Adding test_sysman_memory
-- Adding test_sysman_fabric
-- Adding test_sysman_device
-- Adding test_sysman_psu
-- Adding test_sysman_fan
-- Adding test_sysman_led
-- Adding test_sysman_ras
-- Adding test_sysman_engine
-- Adding test_sysman_temperature
-- Adding test_sysman_firmware
-- Adding test_sysman_overclocking
-- Adding test_sysman_scheduler
-- Adding test_sysman_performance
-- Adding test_cmdlist_errors
-- Adding test_cmdqueue_errors
-- Adding test_module_errors
-- Adding test_device_errors
-- Adding test_driver_errors
-- Adding test_api_ltracing
-- Adding test_memory_allocation
-- Configuring incomplete, errors occurred!
See also "/home/gta/level-zero-tests-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/gta/level-zero-tests-master/build/CMakeFiles/CMakeError.log".
`

**Comment by bmyates** [comment]
```
CMake Error at CMakeLists.txt:38 (add_subdirectory):
The source directory /home/gta/level-zero-tests-master/third_party/googletest does not contain a CMakeLists.txt file.
```

This looks like the problem.  That directory is a git submodule that should be initialized by cmake, but looks like it got out of sync somehow and is not initialized.  I'd suggest deleting your repo, getting a fresh clone, and trying cmake again.

**Comment by singhalshubham03** [comment]
I tried with download the fresh source code but the issue is still same no change in error message

Please see once the CMakeError.log in that it shows undefined reference to p_thread_create and some more pthread functions

The error is related to that I think.

**Comment by Jemale** [comment]
@singhalshubham03 is this still an issue?
