### ISSUE TITLE
Install step does not install files to expected places or with expected access rights

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero-tests#15]
When doing build with:
```
$ cmake -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=/usr/local \
   -DBUILD_ZE_PERF_TESTS_ONLY=1 \
   -DENABLE_ZESYSMAN=1
$ make install
```

"zesysman" is installed to "/usr/local/zesysman/zesysman" and perf tests directly to "/usr/local", these executables do not go under "/usr/local/bin" as expected, so that they would be in $PATH.

Additionally, SPIRV "*.spv" files associated with perf tests, and ""zesysman" directory containing python code used by "zesysman", are also installed directly to "/usr/local", not under "/usr/local/lib/<project>" (if they are arch-dependent) or "/usr/local/share/<project>" (if arch-independent) as expected.

Expected = according to to the applicable standards: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

Finally, "zesysman" is installed with 700 access rights instead of expected 755, so container users cannot run it without manually fixing that.

**Comment by lisanna-dettwyler** [comment]
At https://github.com/oneapi-src/level-zero-tests/blob/master/BUILD.md#building we show setting `CMAKE_INSTALL_PREFIX=$PWD/../out`. You are not supposed to attempt to install these tests into system paths.

**Comment by eero-t** [comment]
> You are not supposed to attempt to install these tests into system paths.

Why this project is published in the first place, if the test tools provided by it are not supposed to be production quality enough to be installed to a path in `$PATH`?
