### ISSUE TITLE
Broken Boost detection for perf tests

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero-tests#16]
Some of the perf tests require Boost: https://github.com/oneapi-src/level-zero-tests/blob/master/perf_tests/CMakeLists.txt

But Boost detection is *disabled* when building just perf tests: https://github.com/oneapi-src/level-zero-tests/blob/master/CMakeLists.txt#L44

**Comment by jandres742** [comment]
@eero-t thanks. Yes, in this case, recommendation is to build the complete repo with boost. I can add a comment in the BUILD file indicating this.

**Comment by jandres742** [comment]
I will also add a change to skip gracefully the tests needing boost.

**Comment by eero-t** [comment]
> Yes, in this case, recommendation is to build the complete repo with boost. I can add a comment in the BUILD file indicating this.

Why you are limiting CMake boost checks only to complete repo build?  Why not just check boost always, and only fail complete repo build when Boost is missing?

> I will also add a change to skip gracefully the tests needing boost.

Perf tests build already handles Boost missing, as the current problem is that Boost detection is not done when only perf tests are built...

**Comment by gdtratnack** [comment]
Addressed under this commit: https://github.com/oneapi-src/level-zero-tests/commit/faf9363d1022930ac63b99517f1d9bd0ef8b5dcc

Boost find_package is now included as part of -DBUILD_ZE_PERF_TESTS_ONLY=1. It is marked as optional though, so if boost is not found the tests that require boost will be skipped. We have added a warning message in the CMake to state which tests are being skipped.

**Comment by gdtratnack** [comment]
If you agree that this fix is sufficient please go ahead and close this issue. 

Thanks!

**Comment by eero-t** [comment]
Thanks, works fine now!
