### ISSUE TITLE
Broken perf tests build with OpenCL present

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero-tests#17]
When project is configured with "-DREQUIRE_OPENCL_BENCHMARKS=1 -DBUILD_ZE_PERF_TESTS_ONLY=1", build fails to:
```
CMake Error at CMakeLists.txt:191 (add_executable):
  Target "ze_cabe" links to target "level_zero_tests::logging" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:267 (add_lzt_test_executable)
  perf_tests/ze_cabe/CMakeLists.txt:50 (add_lzt_test)

CMake Error at CMakeLists.txt:191 (add_executable):
  Target "ze_cabe" links to target "level_zero_tests::image" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:267 (add_lzt_test_executable)
  perf_tests/ze_cabe/CMakeLists.txt:50 (add_lzt_test)
```
=> Build dependencies declared in CMake are broken for "ze_cabe".

**Comment by jandres742** [comment]
@eero-t thanks. thx. Let us see what we can do about it.

**Comment by eero-t** [comment]
cl_image_copy seems also to depend on things outside of perf tests dir: https://github.com/oneapi-src/level-zero-tests/blob/master/perf_tests/cl_image_copy/CMakeLists.txt

**Comment by gdtratnack** [comment]
Addressed under this commit: https://github.com/oneapi-src/level-zero-tests/commit/faf9363d1022930ac63b99517f1d9bd0ef8b5dcc

Logging and Image libraries are now built as part of -DBUILD_ZE_PERF_TESTS_ONLY=1 which should address these issues. 

Note that these tests also require Boost. If Boost is not found the tests will be skipped. We have added a warning message in the CMake that should state that the tests are skipped in this case.

**Comment by gdtratnack** [comment]
If you agree that this fix is sufficient please go ahead and mark this issue as closed.  

Thanks!

**Comment by eero-t** [comment]
Thanks, works fine now!   See #19 though.
