### ISSUE TITLE
Disabling Gmock (-DBUILD_GMOCK=0) fails (perf tests) build

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero-tests#18]
configuring project with "-DBUILD_GMOCK=0 -DBUILD_ZE_PERF_TESTS_ONLY=1", fails in build with:
```
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Cloning into '/home/nobody/source/level-zero-tests/third_party/googletest'...
Submodule path 'third_party/googletest': checked out '2fe3bd994b3189899d93f1d5a881e725e046fdc2'
-- Found PythonInterp: /usr/bin/python3.8 (found version "3.8.10") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:40 (add_library):
  add_library cannot create ALIAS target "GMock::GMock" because target
  "gmock" does not already exist.
```
Please remove broken build config options, or fix them.

PS. What I really would like to do is disable googletest (as it does not seem to be used for perf-tests, but it still gets pulled from internet and built), but there's no option for that, so I happened to test Gmock option instead.

**Comment by gdtratnack** [comment]
This flag is not supported by our build system, it is an option in the third party GTest build.
Our build always assumes that it is set to ON. 

That being said, we may be able to build the perf tests without building GTest. Will look into it.

**Comment by eero-t** [comment]
Great, thanks!

(I hate things that pull stuff from internet during building, instead of just failing, and there being documentation on what they need.)

**Comment by gdtratnack** [comment]
If you agree that this fix is sufficient please go ahead and mark this issue as closed.  

Thanks!

**Comment by eero-t** [comment]
Thanks, works fine now, and no extra things are downloaded during build.
