### ISSUE TITLE
Incorrect order of destruction of kernel and module in conformance_tests/core/test_event/src/test_event_profiling.cpp

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [oneapi-src/level-zero-tests#21]
In [EventProfilingTests::TearDown()](https://github.com/oneapi-src/level-zero-tests/blob/773b6605ff2d6d0b4350e4a03d5f19e70b0239ec/conformance_tests/core/test_event/src/test_event_profiling.cpp#L66) `module` destroyed before `kernel` that created from the module. In the [spec](https://spec.oneapi.io/level-zero/latest/core/api.html#_CPPv415zeModuleDestroy18ze_module_handle_t) we have

> The application must destroy all kernel and build log handles created from the module before destroying the module itself.

**Comment by Alexandr-Konovalov** [comment]
And same issue exists in [GivenKernelEventWhenUsingEventToSyncThenCacheIsCoherent](https://github.com/oneapi-src/level-zero-tests/blob/773b6605ff2d6d0b4350e4a03d5f19e70b0239ec/conformance_tests/core/test_event/src/test_event_profiling.cpp#L308).

**Comment by jandres742** [comment]
thanks @Alexandr-Konovalov . Yes, you are correct.. We will take care of it.

**Comment by Jemale** [comment]
Fixed in https://github.com/oneapi-src/level-zero-tests/commit/895a198498270a31d4b273457a92e8fd91b28c74
