### ISSUE TITLE
Different contexts for allocating/releasing memory in ConcurrentCommandQueueExecutionTests.GivenMultipleCommandQueuesWhenExecutedOnSameDeviceResultsAreCorrect

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [oneapi-src/level-zero-tests#23]
Dear colleagues,

I see that test [GivenMultipleCommandQueuesWhenExecutedOnSameDeviceResultsAreCorrect](https://github.com/oneapi-src/level-zero-tests/blob/773b6605ff2d6d0b4350e4a03d5f19e70b0239ec/conformance_tests/core/test_cmdqueue/src/test_cmdqueue.cpp#L818) failed on [releasing memory](https://github.com/oneapi-src/level-zero-tests/blob/773b6605ff2d6d0b4350e4a03d5f19e70b0239ec/conformance_tests/core/test_cmdqueue/src/test_cmdqueue.cpp#L890) because the memory is [allocated](https://github.com/oneapi-src/level-zero-tests/blob/773b6605ff2d6d0b4350e4a03d5f19e70b0239ec/conformance_tests/core/test_cmdqueue/src/test_cmdqueue.cpp#L852) from a context that is just created, [while ](https://github.com/oneapi-src/level-zero-tests/blob/773b6605ff2d6d0b4350e4a03d5f19e70b0239ec/utils/test_harness/src/test_harness_memory.cpp#L214) `lzt::free_memory(queue.src_buff);` uses context from `lzt::get_default_context()` that is a different one.

**Comment by jandres742** [comment]
thanks @Alexandr-Konovalov . Your analysis seems correct. We will correct the test, thanks!

**Comment by kboyarinov** [comment]
@jandres742,

The same issue appears in [`test_context.cpp`](https://github.com/oneapi-src/level-zero-tests/blob/master/conformance_tests/core/test_context/src/test_context.cpp#:~:text=lzt%3A%3Afree_memory(buffer)%3B). `context` object should be explicitly provided to `lzt::free_memory(buffer)`.

**Comment by Jemale** [comment]
fixed in https://github.com/oneapi-src/level-zero-tests/commit/b447e1491c4a563a08b3211b765e59ef8bb9b3dd
