### ISSUE TITLE
Suspicious ze_event_desc_t initialization in test_cmdlist_immediate.cpp

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [oneapi-src/level-zero-tests#24]
Dear colleagues,

event_desc [initialization](https://github.com/oneapi-src/level-zero-tests/blob/773b6605ff2d6d0b4350e4a03d5f19e70b0239ec/conformance_tests/core/test_cmdlist/src/test_cmdlist_immediate.cpp#LL178C3-L180C67)
```
ze_event_desc_t event_desc = {ZE_STRUCTURE_TYPE_EVENT_DESC, nullptr,
                                ZE_COMMAND_QUEUE_PRIORITY_NORMAL,
                                ZE_COMMAND_QUEUE_PRIORITY_NORMAL};
```
looks suspicious because `ze_event_desc_t` has 5 members, while only 4 is presented, `ZE_COMMAND_QUEUE_PRIORITY_NORMAL` is not supposed to initialize `ze_event_scope_flags_t` and index of the event within the pool, as it done now.

**Comment by jandres742** [comment]
thanks @Alexandr-Konovalov . Yes, this definitely is a bug in the test (possibly as a result of copy/paste). We will take care of it.

**Comment by Jemale** [comment]
Fixed via https://github.com/oneapi-src/level-zero-tests/commit/9a1dac4a6e00ac994cb041c88cd57a0c907c7005
