### ISSUE TITLE
Incorrect index in zeEventCreate() in GivenConcurrentLogicalCommandQueuesWhenStartSynchronizedThenHighPriorityCompletesFirst

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [oneapi-src/level-zero-tests#26]
ze_event_desc_t::index in

```
        event_desc.index = index++;
        auto event_compute_low = lzt::create_event(ep_time, event_desc);
        event_compute_lows.push_back(event_compute_low);
```
[should be initialized](https://github.com/oneapi-src/level-zero-tests/blob/0a5402244b97828938cf291b169faca0cd72958f/conformance_tests/core/test_cmdqueue/src/test_cmdqueue.cpp#L491) by pre-increment, as currently 1st element of `event_compute_lows` and `event_compute_high` is same event, because they created using same index.

**Comment by KapiX** [comment]
Fixed in 93ee6d66f44087093c9cb1fe9676047834416c59.
