### ISSUE TITLE
Can't execute.

### ISSUE THREAD

**Issue by kugimiyamikado** [oneapi-src/level-zero-tests#32]
I install all of packages (googletest booster1.6.5 )that run will show error 2013265921.
![rpviewer (2)](https://github.com/oneapi-src/level-zero-tests/assets/148205503/2f467c19-93a2-4db1-9b0a-0303d77bb427)

Kindly help me to fix up this problem.
Or kindly give me some suggestion.
Thanks!

**Comment by eero-t** [comment]
Your error:
```
>>> hex(2013265921)
'0x78000001'
```

Is `ZE_RESULT_ERROR_UNINITIALIZED` i.e. driver not being initialized: https://github.com/oneapi-src/level-zero/blob/master/include/ze_api.h#L217

You need to install level-zero driver/backend to use level-zero programs. Drivers are available from:
- latest Debian & Fedora distro versions repositories: https://github.com/oneapi-src/level-zero/issues/73#issuecomment-1357956650
- compute-runtime driver project: https://github.com/intel/compute-runtime/releases
- Intel driver repositories (older distros): https://dgpu-docs.intel.com/

**Comment by Jemale** [comment]
Closing this. @kugimiyamikado if you're having trouble still create different issues
