### ISSUE TITLE
tests repo writes to manifest.txt in install dir at cmake time

### ISSUE THREAD

**Issue by airlied** [oneapi-src/level-zero-tests#4]
When running cmake .. with a prefix set, it tries to write to <prefix>/manifest.txt

This shouldn't happen, you should never write to the CMAKE_INSTALL_PREFIX at the cmake point.

function(add_lzt_test)
   file(APPEND
      "${CMAKE_INSTALL_PREFIX}/manifest.txt"

is wrong.

**Comment by LisannaAtIntel** [comment]
Thanks for pointing that out! e693f56 should resolve this. Feel free to reopen this issue if you're still seeing problems.
