### ISSUE TITLE
module create passes uninitialised constants

### ISSUE THREAD

**Issue by airlied** [oneapi-src/level-zero-tests#5]
utils/test_harness/src/test_harness_module.cpp:create_module

puts 
module_constants
on the stack but never initialises it.

**Comment by airlied** [comment]
The ze_module.h header does say.
  ///< This must be set to nullptr if no specialization constants are
  ///< provided.

Also if a shader expects specialisation constants do they have to be provided, if they aren't what is the expected behaviour.

GivenValidSpecConstantsWhenCreatingModuleThenExpectSpecConstantInKernelGetsUpdates
test seems to do that, I suppose it's like vulkan
"It is legal for a SPIR-V module with specializations to be compiled into a pipeline where no specialization info was provided. SPIR-V specialization constants contain default values such that if a specialization is not provided, the default value will be used."

**Comment by bmyates** [comment]
There's a bug in the current 0.91 level zero spec and loader that requires `pConstants` to be non-null even when specialization constants are not required by the module. The code in the test here is a work around for that issue. 

A fix for this will be coming soon.  See: https://github.com/oneapi-src/level-zero/issues/12

**Comment by airlied** [comment]
Can we at least memset it to 0 contents for now, as it is the contents are undefined stack memoty,

**Comment by bmyates** [comment]
Sure, we will push a fix to zero-initialize it soon.
