### ISSUE TITLE
Errors encountered while following build instructions in master/CONTRIBUTING.md

### ISSUE THREAD

**Issue by aarontcopal2** [oneapi-src/level-zero-tests#6]
Hello, i wanted to create .spv files and was following the installation instructions mentioned in was following the instuctions specified at https://github.com/oneapi-src/level-zero-tests/blob/master/CONTRIBUTING.md. my `make `command fails with this error.

```
$ make -j 4
...
...
/gpfs/jlse-fs0/users/aarontcopal2/software/llvm/lib/Support/Path.cpp: In function 'llvm::sys::fs::file_magic llvm::sys::fs::identify_magic(llvm::StringRef)':
/gpfs/jlse-fs0/users/aarontcopal2/software/llvm/lib/Support/Path.cpp:1025:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1025 |       if (Magic[1] == 0x01)
      |       ^~
/gpfs/jlse-fs0/users/aarontcopal2/software/llvm/lib/Support/Path.cpp:1028:5: note: here
 1028 |     case 0x90: // PA-RISC Windows
      |     ^~~~
[  5%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/TargetRegistry.cpp.o
[  5%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/ThreadLocal.cpp.o
[  5%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Threading.cpp.o
[  5%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/TimeValue.cpp.o
[  5%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Valgrind.cpp.o
[  5%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Watchdog.cpp.o
[  5%] Linking CXX static library ../libLLVMSupport.a
[  5%] Built target LLVMSupport
make: *** [all] Error 2
```

Any help on this issue would be appreciated.

**Comment by bmyates** [comment]
Hi, could you please add your full build log as an attachment? I will take a look and see if I can provide any help.

**Comment by aarontcopal2** [comment]
Sure, attached below are the logs for cmake and make commands

[llvm_cmake.log](https://github.com/oneapi-src/level-zero-tests/files/5052501/llvm_cmake.log)
[llvm_make.log](https://github.com/oneapi-src/level-zero-tests/files/5052476/llvm_make.log)

**Comment by bmyates** [comment]
Hmmm.... not sure. i'm not able to reproduce the issue here.

**Comment by aarontcopal2** [comment]
what versions of gcc, make and cmake are you using?

**Comment by bmyates** [comment]
I'm running ubuntu 18... looks like it has 

cmake 3.10
gcc 7.5.0
make 4.1
